name = "elysium-network"
pages_build_output_dir = "_site"
compatibility_date = "2024-09-01"

[[d1_databases]]
binding = "DB"
database_name = "elysium-votes"
database_id = "fe7d7777-297b-4f83-88ec-4d2f2fa48872"
