// Content edits land in D1 immediately, but the public pages are static
// HTML generated by Eleventy at build time -- every save that affects a
// public page needs a fresh Cloudflare Pages build to actually go live.
// This used to require staff to click "Publish changes" manually on the
// dashboard (functions/api/admin/rebuild.js, still there for that button);
// now every content-mutating admin endpoint below also calls
// scheduleRebuild(env) via waitUntil so it happens automatically.
//
// Cloudflare Pages "Deploy Hooks" (a URL you POST to) can only be created
// through the dashboard -- there's no API for it -- so this calls the same
// "create deployment" endpoint the dashboard's deploy hooks ultimately use,
// directly, authenticated with a scoped API token instead.
export async function triggerDeploy(env) {
  if (!env.CF_API_TOKEN || !env.CF_ACCOUNT_ID) {
    return { ok: false, error: 'CF_API_TOKEN / CF_ACCOUNT_ID is not configured' };
  }
  const projectName = env.CF_PAGES_PROJECT_NAME || 'elysiumnetwork';
  const res = await fetch(
    `https://api.cloudflare.com/client/v4/accounts/${env.CF_ACCOUNT_ID}/pages/projects/${projectName}/deployments`,
    { method: 'POST', headers: { Authorization: `Bearer ${env.CF_API_TOKEN}` } },
  );
  const data = await res.json().catch(() => null);
  if (!res.ok || !data?.success) {
    return { ok: false, status: res.status, detail: data?.errors };
  }
  return { ok: true, deploymentId: data.result?.id };
}

// Fire-and-forget wrapper for automatic rebuilds after a content save,
// meant to be passed to waitUntil -- a rebuild hiccup (rate limit, a
// transient Cloudflare API error) must never fail the actual content save,
// so failures are swallowed here rather than surfaced to the caller.
export async function scheduleRebuild(env) {
  try {
    const result = await triggerDeploy(env);
    if (!result.ok) console.warn('Auto-rebuild trigger failed:', result.error || result.detail || result.status);
  } catch (err) {
    console.warn('Auto-rebuild trigger threw:', err);
  }
}
