-- Seed: current live content, migrated from src/_data/site.js

-- branches
INSERT INTO branches (slug, sort_order, name, name_native, country, city, flag, accent, tz, lat, lon, iso_n3, oid, type, status, tagline, about, focus_json, people_json, email, phone, address, website) VALUES ('ukraine', 0, 'Elysium+ Ukraine', 'ГО «Елізіум+»', 'Ukraine', 'Chernihiv', '🇺🇦', '#FFD23F', 'Europe/Kyiv', '51.50°N', '31.29°E', '804', 'E10407340', 'Civil Organisation (NGO)', 'Founding organisation', 'Where the network began.', 'Elysium+ began as a school initiative in 2020 and grew into a registered NGO in Ukraine in 2025. From the start the mission has stayed the same: to promote European values, intercultural dialogue, civic engagement and personal development among young people. Today it works at the intersection of youth empowerment, digital development, international mobility and non-formal education — and acts as the sending organisation for the wider network.', '["Youth awareness & civic participation","Non-formal education programmes","Digital engagement & European cooperation","Support for displaced & rural youth"]', '[{"name":"Anton Rubanenko","role":"Head of the NGO · Project Manager","email":"rubanenko@elysium.ngo"},{"name":"Jonas Hanke","role":"Youth Worker · IT Support","email":"hanke@elysium.ngo"}]', 'contact@elysium.ngo', '+380 93 861 43 05', 'Peremohy Avenue 119A, apt. 307, 14000 Chernihiv, Ukraine', NULL);
INSERT INTO branches (slug, sort_order, name, name_native, country, city, flag, accent, tz, lat, lon, iso_n3, oid, type, status, tagline, about, focus_json, people_json, email, phone, address, website) VALUES ('poland', 1, 'Elysium+ Poland', 'Elysium+ Polska', 'Poland', 'Mińsk Mazowiecki', '🇵🇱', '#FF5C72', 'Europe/Warsaw', '52.18°N', '21.57°E', '616', 'E10418127', 'Informal Group of Young People', 'Active branch', 'Human rights at the core.', 'Elysium+ Polska is a youth-focused, non-profit initiative committed to human rights, democratic values and social inclusion. Its work is grounded in dignity, equality, solidarity and respect for diversity, and it uses youth engagement and non-formal learning to empower young people — especially those with fewer opportunities — to build awareness, responsibility and active citizenship.', '["Human rights education","Democratic participation","Social inclusion","Intercultural understanding"]', '[{"name":"Aleksandra Sulejewska","role":"Group Coordinator · Communication","email":"sulejewska.pl@elysium.ngo"},{"name":"Błażej Wypart","role":"Youth Worker · Project Manager","email":"contact.pl@elysium.ngo"}]', 'contact.pl@elysium.ngo', '+48 781 147 586', 'Jana Łupińskiego 5/1, 05-300 Mińsk Mazowiecki, Poland', NULL);
INSERT INTO branches (slug, sort_order, name, name_native, country, city, flag, accent, tz, lat, lon, iso_n3, oid, type, status, tagline, about, focus_json, people_json, email, phone, address, website) VALUES ('italy', 2, 'Elysium+ Italy', 'Elysium+ Italia', 'Italy', 'San Pietro Val Lemina', '🇮🇹', '#34D399', 'Europe/Rome', '44.92°N', '7.25°E', '380', 'E10417547', 'Informal Group of Young People', 'Active branch', 'Mobility as a bridge.', 'Elysium+ Italy is a youth-focused, non-profit initiative promoting youth mobility, social inclusion and active citizenship. It treats mobility as a key instrument for intercultural understanding and democratic participation across Europe, and aligns its work with SDG 10 (Reduced Inequalities) and SDG 11 (Sustainable Cities & Communities), with particular attention to young people with fewer opportunities.', '["Inclusive youth mobility","Active citizenship","Intercultural learning","SDG 10 & SDG 11"]', '[{"name":"Andrea Dal Molin","role":"Group Coordinator","email":"dalmolin.it@elysium.ngo"},{"name":"Anton Rubanenko","role":"Network Coordinator","email":"rubanenko@elysium.ngo"}]', 'contact@elysium.ngo', '+39 392 7120202', 'Via P.G. Frassati 9, 10060 San Pietro Val Lemina, Italy', NULL);
INSERT INTO branches (slug, sort_order, name, name_native, country, city, flag, accent, tz, lat, lon, iso_n3, oid, type, status, tagline, about, focus_json, people_json, email, phone, address, website) VALUES ('germany', 3, 'Astra', 'Astra gUG (haftungsbeschränkt) i.Gr.', 'Germany', 'Leipzig', '🇩🇪', '#8B7CFF', 'Europe/Berlin', '51.34°N', '12.37°E', '276', 'E10407336', 'gemeinnützige UG (in formation)', 'In formation', 'The German branch, in the making.', 'Astra is the German branch of the network, being established as a gemeinnützige Unternehmergesellschaft (gUG) with its registered seat in Aachen and operations in Leipzig. It runs fully funded Erasmus+ projects across Europe — exchanges, training and youth-led activities — built on inclusion, democracy and exchange. Registration in the Handelsregister is in progress, so the entity currently carries the "i.Gr." (in formation) suffix.', '["Erasmus+ project management","Youth exchanges & training","DiscoverEU","Leipzig & eastern Germany focus"]', '[{"name":"Jonas Hanke","role":"Founder · Managing Director","email":"hanke@elysium.ngo"},{"name":"Anton Rubanenko","role":"Co-founder","email":"rubanenko@elysium.ngo"}]', 'hanke@elysium.ngo', NULL, 'Registered seat: Aachen · Operations: Leipzig, Germany', 'https://astra.ngo');

-- team_members
INSERT INTO team_members (id, sort_order, name, role, image, focal_y, bio) VALUES ('anton-rubanenko', 0, 'Anton Rubanenko', 'Founder & Project Manager', '/assets/team/anton-rubanenko.jpg', '10%', 'Founder of Elysium+ and a youth activist focused on democracy, human rights and cultural exchange. He has joined more than 20 Erasmus+ projects and visited 40+ countries, building the partnerships that empower young people across Europe.');
INSERT INTO team_members (id, sort_order, name, role, image, focal_y, bio) VALUES ('jonas-hanke', 1, 'Jonas Hanke', 'Co-founder & IT Specialist', '/assets/team/jonas-hanke.jpg', '48%', 'Co-founder with a passion for travel, media and cultural discovery, and managing director of the German branch, Astra. Inspired by brutalist architecture, he connects culture, design and youth engagement — and keeps the network''s digital infrastructure running.');
INSERT INTO team_members (id, sort_order, name, role, image, focal_y, bio) VALUES ('erg-n-eraslan', 2, 'Ergün Eraslan', 'Associate Member', '/assets/team/ergun-eraslan.jpg', '15%', 'Youth activist with a background in mechanical engineering. Passionate about equality, innovation and cultural exchange, he has taken part in initiatives addressing discrimination and promoting inclusion.');
INSERT INTO team_members (id, sort_order, name, role, image, focal_y, bio) VALUES ('nourhan-said', 3, 'Nourhan Said', 'Associate Member', '/assets/team/nourhan-said.jpg', '12%', 'U.S. Department of State alumna who served with a child-focused organisation in the United States. Her research focuses on migration, gender and refugee studies — the intersection of mobility, protection frameworks and social policy.');

-- faqs
INSERT INTO faqs (id, sort_order, question, answer) VALUES ('faq-1', 0, 'What is Elysium+?', 'Elysium+ is a youth-focused non-profit network that creates opportunities for young people to learn, travel and grow through international mobility and non-formal education. We work across Europe with partners, youth workers and organisations to support inclusion, creativity, digital development and intercultural understanding.');
INSERT INTO faqs (id, sort_order, question, answer) VALUES ('faq-2', 1, 'Do I need experience to join your projects?', 'No. Most projects are designed for beginners and for young people taking part in international activities for the first time. What matters most is motivation, openness and the desire to learn. Some specialised trainings have specific requirements, which we always indicate in advance.');
INSERT INTO faqs (id, sort_order, question, answer) VALUES ('faq-3', 2, 'How is Elysium+ funded?', 'Through international project grants — especially Erasmus+ — partnerships with European organisations, and support from local and international collaborators. Community contributions help too; see the Support Us page for ways to help.');
INSERT INTO faqs (id, sort_order, question, answer) VALUES ('faq-4', 3, 'How can I contribute?', 'Beyond donations, you can volunteer, share your skills, or help spread the word about our work. We welcome people interested in online events, creative projects, workshops and digital activities. If you have an idea, we''re always open to new proposals.');

-- calls (from src/calls.njk)
INSERT INTO calls (id, sort_order, title, branch_slug, status, deadline_label, summary, link, link_label) VALUES ('call-1', 0, 'Democracy on TrackS (DOTS)', 'germany', 'closed', 'Applications closed 10 July 2026', 'Five seats on a ten-day, fully funded rail journey from Berlin to Strasbourg — visiting the Bundestag, the European Commission, the Court of Justice and the European Parliament along the way. Open to young people aged 18–21 legally resident in Germany. No CV, no portfolio — just curiosity and a willingness to document the journey.', 'https://hub.elysium.ngo/dots', 'Project page');
