module.exports = [
  { title: 'Home', url: '/', group: 'Pages', blurb: 'Elysium+ — European youth network rooted in Ukraine.' },
  { title: 'About', url: '/about/', group: 'Pages', blurb: 'Our story, the team, and frequently asked questions.' },
  { title: 'Active calls', url: '/calls/', group: 'Pages', blurb: 'Open exchanges, trainings and youth-led opportunities.' },
  { title: 'Support Us', url: '/support/', group: 'Pages', blurb: 'Volunteer, promote our work, or donate.' },
  { title: 'Contact', url: '/contact/', group: 'Pages', blurb: 'Email the network or a specific branch.' },
  { title: 'Values & Standards', url: '/standards/', group: 'Pages', blurb: 'The principles every member and partner agrees to.' },
  { title: 'Equity Workplan', url: '/commitments/', group: 'Pages', blurb: 'Our commitments in practice, not just on paper.' },
  { title: 'Privacy Policy', url: '/privacy/', group: 'Pages', blurb: 'How we collect, use and protect your data (GDPR).' },
  { title: 'Blog', url: '/blog/', group: 'Pages', blurb: 'Stories and announcements from across the network.' },
  { title: 'Events', url: '/events/', group: 'Pages', blurb: 'Upcoming exchanges and trainings, with RSVP.' },
  { title: 'Resources', url: '/resources/', group: 'Pages', blurb: 'Annual reports, toolkits and guides to download.' },
  { title: 'Against the War', url: '/against-the-war/', group: 'Pages', blurb: "Documenting Russia's invasion and its impact on our home region." },
  { title: 'Youth Peacebuilding Partnership', url: '/projects/peacebuilding/', group: 'Network', blurb: 'Astra’s Erasmus+ partner-recruitment project.' },
  { title: 'Elysium+ Ukraine', url: '/ukraine/', group: 'Network', blurb: 'Chernihiv — the founding organisation.' },
  { title: 'Elysium+ Poland', url: '/poland/', group: 'Network', blurb: 'Mińsk Mazowiecki — human rights at the core.' },
  { title: 'Elysium+ Italy', url: '/italy/', group: 'Network', blurb: 'San Pietro Val Lemina — mobility as a bridge.' },
  { title: 'Astra (Germany)', url: '/germany/', group: 'Network', blurb: 'Leipzig — the German branch, in the making.' },
];
