const contact_email = 'contact@elysium.ngo';

module.exports = {
  network_name: 'Elysium+',
  network_full: 'Elysium+ Network',
  tagline: 'Empowering young people to create positive change',
  founded_year: 2020,
  contact_email,
  logo: 'https://elysium.ngo/wp-content/uploads/2025/10/Elysium-1600-x-400-px-1600-x-1600-px-Background-Removed-2-2-1-1024x1024.png',
  join_form: 'mailto:' + contact_email + '?subject=' + encodeURIComponent('I want to join Elysium+'),
  hub: 'https://hub.elysium.ngo/',
  astra_site: 'https://astra.ngo',

  socials: [
    { label: 'Instagram', url: 'https://www.instagram.com/beyondborders.ngo', icon: 'instagram' },
    { label: 'Facebook', url: 'https://www.facebook.com/profile.php?id=61582982678651', icon: 'facebook' },
    { label: 'Telegram', url: 'https://t.me/ElysiumNGO', icon: 'telegram' },
    { label: 'WhatsApp', url: 'https://wa.me/message/PK3TQ4FNCQ5VC1', icon: 'whatsapp' },
    { label: 'Email', url: 'mailto:contact@elysium.ngo', icon: 'mail' },
  ],

  mission: 'Our mission is to empower young people through education, mobility and active participation. We believe every young person has the right to learn, explore and shape their own future — regardless of background or nationality. Guided by the European values of democracy, equality, solidarity and respect for human dignity, we create opportunities for growth, intercultural understanding and civic engagement.',
  vision: 'A Europe where young people lead change — a continent united by cooperation, inclusion and innovation. We work toward a society where education and lifelong learning are accessible to all, and where youth are active contributors to sustainable development, peace and social justice.',
  values_short: [
    ['Freedom & equality', 'Equal access to education, opportunities and participation.'],
    ['Solidarity & inclusion', 'Unity, respect and understanding across diverse cultures.'],
    ['Sustainability', 'Initiatives that protect both people and the planet.'],
    ['Youth empowerment', 'Self-development, creativity and leadership in every young person.'],
  ],

  themes: [
    { icon: 'globe', title: 'International mobility', text: 'Youth exchanges, training courses and DiscoverEU journeys that send young people across Europe.' },
    { icon: 'spark', title: 'Non-formal education', text: 'Interactive, learning-by-doing sessions on media literacy, leadership and civic life.' },
    { icon: 'heart', title: 'Inclusion', text: 'Priority for young people with fewer opportunities — displacement, social or mobility barriers.' },
    { icon: 'monitor', title: 'Digital engagement', text: 'Online content and sessions that reach rural youth and IDP communities.' },
    { icon: 'vote', title: 'Democratic participation', text: 'Campaigns and activities that give young people a real voice in their communities.' },
    { icon: 'leaf', title: 'Sustainability', text: 'Ecological responsibility woven through our programmes and everyday practice.' },
  ],

  branches: [
    {
      tz: 'Europe/Kyiv', lat: '51.50°N', lon: '31.29°E',
      slug: 'ukraine', flag: '🇺🇦', iso_n3: '804',
      name: 'Elysium+ Ukraine', name_native: 'ГО «Елізіум+»',
      country: 'Ukraine', city: 'Chernihiv',
      oid: 'E10407340', type: 'Civil Organisation (NGO)',
      status: 'Founding organisation', accent: '#FFD23F',
      tagline: 'Where the network began.',
      about: 'Elysium+ began as a school initiative in 2020 and grew into a registered NGO in Ukraine in 2025. From the start the mission has stayed the same: to promote European values, intercultural dialogue, civic engagement and personal development among young people. Today it works at the intersection of youth empowerment, digital development, international mobility and non-formal education — and acts as the sending organisation for the wider network.',
      focus: ['Youth awareness & civic participation', 'Non-formal education programmes', 'Digital engagement & European cooperation', 'Support for displaced & rural youth'],
      people: [
        { name: 'Anton Rubanenko', role: 'Head of the NGO · Project Manager', email: 'rubanenko@elysium.ngo' },
        { name: 'Jonas Hanke', role: 'Youth Worker · IT Support', email: 'hanke@elysium.ngo' },
      ],
      email: 'contact@elysium.ngo', phone: '+380 93 861 43 05',
      address: 'Peremohy Avenue 119A, apt. 307, 14000 Chernihiv, Ukraine',
      website: null,
    },
    {
      tz: 'Europe/Warsaw', lat: '52.18°N', lon: '21.57°E',
      slug: 'poland', flag: '🇵🇱', iso_n3: '616',
      name: 'Elysium+ Poland', name_native: 'Elysium+ Polska',
      country: 'Poland', city: 'Mińsk Mazowiecki',
      oid: 'E10418127', type: 'Informal Group of Young People',
      status: 'Active branch', accent: '#FF5C72',
      tagline: 'Human rights at the core.',
      about: 'Elysium+ Polska is a youth-focused, non-profit initiative committed to human rights, democratic values and social inclusion. Its work is grounded in dignity, equality, solidarity and respect for diversity, and it uses youth engagement and non-formal learning to empower young people — especially those with fewer opportunities — to build awareness, responsibility and active citizenship.',
      focus: ['Human rights education', 'Democratic participation', 'Social inclusion', 'Intercultural understanding'],
      people: [
        { name: 'Aleksandra Sulejewska', role: 'Group Coordinator · Communication', email: 'sulejewska.pl@elysium.ngo' },
        { name: 'Błażej Wypart', role: 'Youth Worker · Project Manager', email: 'contact.pl@elysium.ngo' },
      ],
      email: 'contact.pl@elysium.ngo', phone: '+48 781 147 586',
      address: 'Jana Łupińskiego 5/1, 05-300 Mińsk Mazowiecki, Poland',
      website: null,
    },
    {
      tz: 'Europe/Rome', lat: '44.92°N', lon: '7.25°E',
      slug: 'italy', flag: '🇮🇹', iso_n3: '380',
      name: 'Elysium+ Italy', name_native: 'Elysium+ Italia',
      country: 'Italy', city: 'San Pietro Val Lemina',
      oid: 'E10417547', type: 'Informal Group of Young People',
      status: 'Active branch', accent: '#34D399',
      tagline: 'Mobility as a bridge.',
      about: 'Elysium+ Italy is a youth-focused, non-profit initiative promoting youth mobility, social inclusion and active citizenship. It treats mobility as a key instrument for intercultural understanding and democratic participation across Europe, and aligns its work with SDG 10 (Reduced Inequalities) and SDG 11 (Sustainable Cities & Communities), with particular attention to young people with fewer opportunities.',
      focus: ['Inclusive youth mobility', 'Active citizenship', 'Intercultural learning', 'SDG 10 & SDG 11'],
      people: [
        { name: 'Andrea Dal Molin', role: 'Group Coordinator', email: 'dalmolin.it@elysium.ngo' },
        { name: 'Anton Rubanenko', role: 'Network Coordinator', email: 'rubanenko@elysium.ngo' },
      ],
      email: 'contact@elysium.ngo', phone: '+39 392 7120202',
      address: 'Via P.G. Frassati 9, 10060 San Pietro Val Lemina, Italy',
      website: null,
    },
    {
      tz: 'Europe/Berlin', lat: '51.34°N', lon: '12.37°E',
      slug: 'germany', flag: '🇩🇪', iso_n3: '276',
      name: 'Astra', name_native: 'Astra gUG (haftungsbeschränkt) i.Gr.',
      country: 'Germany', city: 'Leipzig',
      oid: 'E10407336', type: 'gemeinnützige UG (in formation)',
      status: 'In formation', accent: '#8B7CFF',
      tagline: 'The German branch, in the making.',
      about: 'Astra is the German branch of the network, being established as a gemeinnützige Unternehmergesellschaft (gUG) with its registered seat in Aachen and operations in Leipzig. It runs fully funded Erasmus+ projects across Europe — exchanges, training and youth-led activities — built on inclusion, democracy and exchange. Registration in the Handelsregister is in progress, so the entity currently carries the "i.Gr." (in formation) suffix.',
      focus: ['Erasmus+ project management', 'Youth exchanges & training', 'DiscoverEU', 'Leipzig & eastern Germany focus'],
      people: [
        { name: 'Jonas Hanke', role: 'Founder · Managing Director', email: 'hanke@elysium.ngo' },
        { name: 'Anton Rubanenko', role: 'Co-founder', email: 'rubanenko@elysium.ngo' },
      ],
      email: 'hanke@elysium.ngo', phone: null,
      address: 'Registered seat: Aachen · Operations: Leipzig, Germany',
      website: 'https://astra.ngo',
    },
  ],

  globe_excluded: { '643': 'Russia', '112': 'Belarus' },
  globe_candidates: {
    '008': 'Albania', '020': 'Andorra', '040': 'Austria', '056': 'Belgium', '070': 'Bosnia & Herzegovina',
    '100': 'Bulgaria', '191': 'Croatia', '196': 'Cyprus', '203': 'Czechia', '208': 'Denmark',
    '233': 'Estonia', '246': 'Finland', '250': 'France', '268': 'Georgia', '300': 'Greece',
    '348': 'Hungary', '352': 'Iceland', '372': 'Ireland', '428': 'Latvia', '438': 'Liechtenstein',
    '440': 'Lithuania', '442': 'Luxembourg', '470': 'Malta', '498': 'Moldova', '492': 'Monaco',
    '499': 'Montenegro', '528': 'Netherlands', '807': 'North Macedonia', '578': 'Norway', '620': 'Portugal',
    '642': 'Romania', '674': 'San Marino', '688': 'Serbia', '703': 'Slovakia', '705': 'Slovenia',
    '724': 'Spain', '752': 'Sweden', '756': 'Switzerland', '792': 'Turkey', '826': 'United Kingdom',
    '051': 'Armenia', '031': 'Azerbaijan', '504': 'Morocco', '788': 'Tunisia', '818': 'Egypt',
  },

  team: [
    { name: 'Anton Rubanenko', role: 'Founder & Project Manager',
      image: 'https://elysium.ngo/wp-content/uploads/2025/10/anton-rubanenko.jpg',
      bio: 'Founder of Elysium+ and a youth activist focused on democracy, human rights and cultural exchange. He has joined more than 20 Erasmus+ projects and visited 40+ countries, building the partnerships that empower young people across Europe.' },
    { name: 'Jonas Hanke', role: 'Co-founder & IT Specialist',
      image: 'https://elysium.ngo/wp-content/uploads/2025/10/jonas-hanke.jpeg',
      bio: "Co-founder with a passion for travel, media and cultural discovery, and managing director of the German branch, Astra. Inspired by brutalist architecture, he connects culture, design and youth engagement — and keeps the network's digital infrastructure running." },
    { name: 'Ergün Eraslan', role: 'Associate Member',
      image: 'https://elysium.ngo/wp-content/uploads/2025/11/WhatsApp-Image-2025-11-07-at-22.13.05-edited.jpeg',
      bio: 'Youth activist with a background in mechanical engineering. Passionate about equality, innovation and cultural exchange, he has taken part in initiatives addressing discrimination and promoting inclusion.' },
    { name: 'Nourhan Said', role: 'Associate Member',
      image: 'https://elysium.ngo/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-01-at-15.20.20-1.jpeg',
      bio: 'U.S. Department of State alumna who served with a child-focused organisation in the United States. Her research focuses on migration, gender and refugee studies — the intersection of mobility, protection frameworks and social policy.' },
  ],

  faqs: [
    ['What is Elysium+?', 'Elysium+ is a youth-focused non-profit network that creates opportunities for young people to learn, travel and grow through international mobility and non-formal education. We work across Europe with partners, youth workers and organisations to support inclusion, creativity, digital development and intercultural understanding.'],
    ['Do I need experience to join your projects?', 'No. Most projects are designed for beginners and for young people taking part in international activities for the first time. What matters most is motivation, openness and the desire to learn. Some specialised trainings have specific requirements, which we always indicate in advance.'],
    ['How is Elysium+ funded?', 'Through international project grants — especially Erasmus+ — partnerships with European organisations, and support from local and international collaborators. Community contributions help too; see the Support Us page for ways to help.'],
    ['How can I contribute?', "Beyond donations, you can volunteer, share your skills, or help spread the word about our work. We welcome people interested in online events, creative projects, workshops and digital activities. If you have an idea, we're always open to new proposals."],
  ],

  donation: {
    eur: {
      Beneficiary: '"ELYSIUM+"',
      IBAN: 'UA383220010000026001700010350',
      'SWIFT / BIC': 'UNJSUAUKXXX',
      Bank: 'Universal Bank',
      Address: 'Peremohy Avenue 119A, apt. 307, Chernihiv, Ukraine',
    },
    uah: {
      Organisation: 'NGO "ELYSIUM +"',
      EDRPOU: '46047605',
      Account: 'UA793220010000026006700009054',
      Bank: 'JSC "UNIVERSAL BANK"',
      MFO: '322001',
    },
  },
};
