import { requireStaff } from '../../_lib/guard.js';
import { json } from '../../_lib/http.js';

// Content edits land in D1 immediately, but the actual public pages are
// static HTML generated by Eleventy at build time — so every content save
// needs to trigger a fresh Cloudflare Pages build to actually go live.
// CF_PAGES_DEPLOY_HOOK_URL is a Pages "Deploy Hook" URL (Pages project
// Settings → Builds & deployments → Deploy hooks): POSTing to it queues a
// new build with no other auth needed, so it's safe to hold as a plain env
// var rather than a secret-strength credential.
export async function onRequestPost({ request, env }) {
  const staff = await requireStaff(request, env);
  if (staff instanceof Response) return staff;

  if (!env.CF_PAGES_DEPLOY_HOOK_URL) {
    return json({ error: 'CF_PAGES_DEPLOY_HOOK_URL is not configured' }, { status: 500 });
  }
  const res = await fetch(env.CF_PAGES_DEPLOY_HOOK_URL, { method: 'POST' });
  if (!res.ok) {
    return json({ error: 'Deploy hook returned an error', status: res.status }, { status: 502 });
  }
  return json({ ok: true, triggeredAt: new Date().toISOString() });
}
