import { requireStaff } from '../../_lib/guard.js';
import { json } from '../../_lib/http.js';

// Content edits land in D1 immediately, but the actual public pages are
// static HTML generated by Eleventy at build time — so every content save
// needs to trigger a fresh Cloudflare Pages build to actually go live.
//
// Cloudflare Pages "Deploy Hooks" (a URL you POST to) can only be created
// through the dashboard — there's no API for it — so this calls the same
// "create deployment" endpoint the dashboard's deploy hooks ultimately use,
// directly, authenticated with a scoped API token instead.
export async function onRequestPost({ request, env }) {
  const staff = await requireStaff(request, env);
  if (staff instanceof Response) return staff;

  if (!env.CF_API_TOKEN || !env.CF_ACCOUNT_ID) {
    return json({ error: 'CF_API_TOKEN / CF_ACCOUNT_ID is not configured' }, { status: 500 });
  }

  const projectName = env.CF_PAGES_PROJECT_NAME || 'elysiumnetwork';
  const res = await fetch(
    `https://api.cloudflare.com/client/v4/accounts/${env.CF_ACCOUNT_ID}/pages/projects/${projectName}/deployments`,
    { method: 'POST', headers: { Authorization: `Bearer ${env.CF_API_TOKEN}` } }
  );
  const data = await res.json().catch(() => null);
  if (!res.ok || !data?.success) {
    return json({ error: 'Cloudflare API returned an error', status: res.status, detail: data?.errors }, { status: 502 });
  }
  return json({ ok: true, triggeredAt: new Date().toISOString(), deploymentId: data.result?.id });
}
